import { Urbanist } from "next/font/google";
import "./globals.css"; 

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Notes AI",
  description: "Generated by create Smart Notes AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body className={`${urbanist.className} antialiased`} >{children}</body>
    </html>
  );
}
